image: python:3.9

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA

stages:
  - prepare
  - build
  - lint
  - tests
  - deploy

.ssh_key_template: &ssh_key_template
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
    - mkdir -p ~/.ssh
    - cp $SSH_PRIVATE_KEY ~/.ssh/gitlab_cicd
    - chmod 400 ~/.ssh/gitlab_cicd
  after_script:
    - rm -f ~/.ssh/gitlab_cicd

.docker_login: &docker_login
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.docker_common: &docker_common
  image: docker:stable
  services:
    - docker:dind

build_image:
  stage: build
  <<: *docker_common
  script:
    - cp $CAR_PLATE_ENV .env
    - *docker_login
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $DOCKER_IMAGE:latest --tag ${DOCKER_IMAGE}:${DOCKER_TAG} --tag ${DOCKER_IMAGE}:latest .
    - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
    - docker push ${DOCKER_IMAGE}:latest

lint:
    stage: lint
    <<: *docker_common
    script:
      - *docker_login
      - docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}
      - docker run ${DOCKER_IMAGE}:${DOCKER_TAG} bash -c 'make lint'
    needs:
      - build_image

deploy:
  stage: deploy
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "false"
  script:
    - python3 -m pip install ansible==6.0.0
    - make deploy DOCKER_IMAGE=${DOCKER_IMAGE} DOCKER_TAG=${DOCKER_TAG}

  when: manual
  <<: *ssh_key_template

destroy:
  stage: deploy
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "false"
  script:
    - python3 -m pip install ansible==6.0.0
    - make destroy

  when: manual
  <<: *ssh_key_template
